name: Build and Deploy Docker App

on:
  push:
    branches:
      - master  # триггер на пуш в master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Логин в Docker Hub через secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 3. Сборка и пуш Docker образа
      - name: Build and Push Docker image
        run: |
          # Указываем имя образа
          IMAGE_NAME=myuser/dzenapp:latest
          
          # Сборка образа (корень проекта содержит Dockerfile для всего приложения)
          docker build -t $IMAGE_NAME .
          
          # Пуш в Docker Hub
          docker push $IMAGE_NAME
